# Working on Computer Vision
#### 1) Edge Detection

In [2]:
import cv2
import numpy as np
import os

In [3]:
!pwd

/home/tanmay/Documents/sirf Adrija ke liye/ComputerVision-Practice


In [9]:
image = cv2.imread('testImage/bruhh.jpeg',0)

In [10]:
print(image)

[[255 255 255 ... 251 251 251]
 [255 255 255 ... 251 251 251]
 [255 255 255 ... 251 251 251]
 ...
 [ 48  51  57 ...   7   6   5]
 [ 56  60  66 ...  12  11  11]
 [ 62  65  70 ...  15  15  15]]


In [11]:
cv2.imshow('image is',image)
canny = cv2.Canny(image, 2,270)
cv2.imshow('Canny',canny)

cv2.waitKey(0)
cv2.destroyAllWindows()

#### 2) Working with Web CAM

In [1]:
import cv2
import numpy as np

In [14]:
def sketch(image):
    img_grey = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    #img_blur = cv2.GaussianBlur(img_grey,(5,5),0)
    canny_edge = cv2.Canny(img_grey, 20,40)
    ret, mask = cv2.threshold(canny_edge, 60,255, cv2.THRESH_BINARY_INV)
    return mask

In [15]:
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    cv2.imshow("Live Sketch", sketch(frame))
    if cv2.waitKey(1) == 13:
        break

cap.release()
cv2.destroyAllWindows()    

#### 3) Working with Contours

In [1]:
import numpy as np
import cv2

In [2]:
image = cv2.imread('/home/tanmay/Desktop/sana.jpeg')
orig_img = image.copy()

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY_INV)

contours, hierarchy = cv2.findContours(thresh.copy(),cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)

for c in contours:
    x,y,w,h = cv2.boundingRect(c)
    cv2.rectangle(orig_img,(x,y), (x+w, y+h), (255,0,0),2)
    cv2.imshow("Bounding Rectangle", orig_img)

cv2.waitKey(1) ==13

for c in contours:
    accuracy = 0.01* cv2.arcLength(c,True)
    approx = cv2.approxPolyDP(c,accuracy, True)
    cv2.drawContours(image,[approx], 0,(0,255,0),2)
    cv2.imshow('Approx Poly DP', image)
    
cv2.waitKey(0)
cv2.destroyAllWindows()

#### 4) Working with contours on video

In [18]:
import cv2
import numpy as np

In [19]:
def imageContours(image):
    org_img = image
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    ret, thresh = cv2.threshold(gray, 127,255, cv2.THRESH_BINARY_INV)
    contours, hierarchy = cv2.findContours(thresh.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)
    for c in contours:
        x,y,w,h = cv2.boundingRect(c)
        cv2.rectangle(org_img,(x,y), (x+w, y+h), (255,0,0),2)
    
    for c in contours:
        accuracy = 0.3* cv2.arcLength(c,True)
        approx = cv2.approxPolyDP(c,accuracy,True)
        mask =cv2.drawContours(image,[approx],0,(0,255,0),2)
        return mask

In [20]:
cap = cv2.VideoCapture(0)
while True:
    ret , frame = cap.read()
    cv2.imshow("Live Contours", imageContours(frame))
    if cv2.waitKey(1)==13:
        break

cv2.destroyAllWindows()        

#### 5) Working with Convex hull